### ISSUE TITLE
pip vs conda install clash

### ISSUE THREAD

**Issue by DaniBodor** [aiproteomics/aiproteomics#16]
pip install does not work for tensorflow==2.6.0 (might work for different version)
conda install does not work for tensorflow-datasets==4.5.2 (I believe it is just not set up for conda at all)

**Comment by raar1** [comment]
Indeed, this has been a source of problems for some time. We will be dropping tfds in favour of specific .msp to model converters that will generate the input data sets instead. This will come as part of the current redesign (now described in the README)
