### ISSUE TITLE
Remove tensor flow datasets from the package

### ISSUE THREAD

**Issue by raar1** [aiproteomics/aiproteomics#18]
As described in the current README (and can be seen in the redesigned pipeline [here](https://github.com/aiproteomics/aiproteomics/blob/main/proposed_aiproteomics_pipeline.png)) we will no longer be using TFDS for the dataset conversion and creation. This is in part because it is a bit of a dependency nightmare currently (although this will no doubt improve as it matures) but also because we wish to have more flexibility for users when it comes to conversions between different input sets, and not rely on tensorflow etc.

In preparation for the creation of the msp2model converters, we should:

- [ ] Remove all tfds related code from the package
- [ ] Make sure it now builds correctly

**Comment by DaniBodor** [comment]
wouldn't it make more sense to remove the code bit by bit as we are replacing it by new code that does the job without tfds? 

Or is that what you meant anyway?
