### ISSUE TITLE
Improve data loading

### ISSUE THREAD

**Issue by dsmits** [aiproteomics/aiproteomics#50]
- Explore tensorflow dataset
- Explore alternatives

Problem: currently whole dataset is loaded in memory, tensorflow dataset might solve this.

There also needs to be functionality to download the dataset from the internet (figshare)

@raar1 can you share the link to the dataset?

**Comment by dsmits** [comment]
related: #49

**Comment by raar1** [comment]
All Prosit data for the 2019 model can be found here: <https://figshare.com/projects/Prosit/35582>

Training and holdout datasets for the fragmentation models are here: <https://figshare.com/articles/dataset/ProteomeTools_-_Prosit_fragmentation_-_Data/6860261>

**Comment by dsmits** [comment]
It looks like there is not a good alternative for tensorflow datasets apart from making something custom.

**Comment by dsmits** [comment]
Closing this issue because more precise issues have been created.
